# 공통 설정

message: "Config 서버의 공통 설정 테스트 메시지 입니다."

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19100/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

shop:
  security:
    jwt:
      access-header-name: Authorization
      header-prefix: "Bearer "
      access-subject: accessJwt
